name: Deploy ASP.NET Core API to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies
        run: dotnet restore src/VibesAndChill.API/VibesAndChill.API.csproj
      - name: Build
        run: dotnet build src/VibesAndChill.API/VibesAndChill.API.csproj --configuration Release --no-restore
      - name: Publish
        run: dotnet publish src/VibesAndChill.API/VibesAndChill.API.csproj --configuration Release --output ./publish --no-build
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish
